apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-sa
  labels:
    app: order-service
    stage: "stage-10"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::165772574557:role/shopsphere-stage9-order-sqs-role"
