apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
    service: product
    stage: "stage-10"
spec:
  type: NodePort
  selector:
    app: product-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081
