apiVersion: v1
kind: ConfigMap
metadata:
  name: shopsphere-common-config
  namespace: shopsphere-stage9
  labels:
    app.kubernetes.io/name: shopsphere
    stage: "stage-10"
data:
  NODE_ENV: "production"
  AWS_REGION: "us-east-1"
  DB_PORT: "5432"
  DB_NAME: "shopspheredb"
  DB_USER: "shopsphere_user"
  DB_SSL: "true"
  REDIS_PORT: "6379"
  DB_HOST: "shopsphere-stage8-postgres.cy9mak0su1oj.us-east-1.rds.amazonaws.com"
  REDIS_HOST: "shopsphere-stage8-redis.ekxmke.0001.use1.cache.amazonaws.com"
  SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/165772574557/shopsphere-stage8-order-processing-queue"
