apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: frontend-service-tgb
  namespace: shopsphere-stage9
spec:
  serviceRef:
    name: frontend-service
    port: 8080
  targetType: instance
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:165772574557:targetgroup/shopsphere-stage10-eks-mono-tg/890b7473842e92cc
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: product-service-tgb
  namespace: shopsphere-stage9
spec:
  serviceRef:
    name: product-service
    port: 8081
  targetType: instance
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:165772574557:targetgroup/shopsphere-stage10-eks-prod-tg/4c2467ae68a9f9b6
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: order-service-tgb
  namespace: shopsphere-stage9
spec:
  serviceRef:
    name: order-service
    port: 8082
  targetType: instance
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:165772574557:targetgroup/shopsphere-stage10-eks-ord-tg/534878bfdc8b1414
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: user-service-tgb
  namespace: shopsphere-stage9
spec:
  serviceRef:
    name: user-service
    port: 8083
  targetType: instance
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:165772574557:targetgroup/shopsphere-stage10-eks-user-tg/0c94cd6eda856b01
